name: letra
description: Ứng dụng du lịch Việt Nam

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # Chuyển path_provider vào đây để code runtime có thể sử dụng
  path_provider: ^2.1.5 

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Icons
  flutter_svg: ^2.0.9
  
  # Image handling
  #image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  gallery_saver_plus: ^3.2.9
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0 # path_provider đã được chuyển lên trên

flutter:
  uses-material-design: true
  
  # Add assets here
  assets:
    - assets/images/
    #- assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"